@startmindmap Anonymous Communication
<style>
root {
    Linecolor black
}
node{
    BackgroundColor: white
}
</style>

* 匿名通信
++ 会议
+++_ CCS
+++_ S&P
+++_ NDSS
+++_ USENIX
+++_ PETS
++ 知名学校
+++_ 普林斯顿大学
+++_ 阿林顿大学
+++_ 马萨诸塞州立大学
+++_ 天主教鲁汶大学
+++_ 普渡大学
+++_ 卢森堡大学
+++_ 亚森工业大学
+++_ ……
-- 匿名通信系统
--- 基于重路由技术
---- Tor
---- I2P
--- 基于 Mix
---- DC-Nets
---- Riffle
----- 私有信息检索
----- 混合洗牌协议
-- 其他相关系统
--- Freenet
----_ 点对点文件检索系统
--- Java Anon Proxy
++ 研究领域
+++ 新型匿名通信系统
++++ 非对称路由
++++ PHI
++++ 折射网络
++++ 诱饵路由
+++ 攻击
++++ 主动攻击
+++++ 端到端确认攻击
+++++ 路由选择攻击
++++++ RAPTOR
++++++ 低资源攻击
++++++ SDoS
++++++ 嗅探攻击
+++++ 旁道攻击
++++ 被动攻击
+++++ 指纹攻击
++++++_ 通过机器学习识别用户访问的网站内容，实现去匿名化
+++++ 关联攻击
++++++_ 对于使用恶意路由的用户，通过各种方式找出流量之间的关系，从而打破不可关联性，实现去匿名化
+++ 防御
++++ 入口节点选择
+++++_ 选取可靠的入口节点以避免信息泄露
++++ 流量分割
+++++_ 将流量分割成多个部分从不同的入口节点甚至网络发送，抵抗指纹攻击
+++ 匿名理论研究
++++ 威胁模型
++++ 攻击度量
+++++_ 对攻击的效果和可行性进行度量分析
++++ 用户激励机制
+++ 匿名系统应用
++++ 统计模型
+++++_ 不侵犯用户隐私的前提下收集 Tor 数据，以供研究
++++ 物联网应用
+++ Tor 优化
++++ 路由选择
+++++_ 更好、更快、更安全的 Tor 路由选择算法
++++ 电路构建优化
++++ 浏览器优化
++++ ……
-- 实用工具
--- 面向用户
---- Tor Broswer
-----_ Tor 浏览器
---- OnionShare
-----_ 基于隐藏服务的文件传输
---- ZeroNet
-----_ 基于 Tor 的分布式网站应用平台（可用于区块链）
---- Briar
-----_ 端到端加密的匿名即时通信
---- Ricochet
-----_ 端到端加密的匿名即时通信
---- Orbot
-----_ 手机端 Tor Onion Proxy
---- OnionBrowser
-----_ 手机端 Tor 浏览器
---- Tor2web
-----_ Tor 反向代理工具（不需要安装 Tor 直接在浏览器访问暗网）
---- GetTor
-----_ 在高度审查的网络通过 SMTP 等协议安装 Tor
---- Multitor
-----_ 快速创建多个 Tor 进程
---- OONI Probe
-----_ 观测网络审查、流量传输
---- Vidalia
-----_ Tor 电路可视化，查看数据传输路径
--- 面向科研
---- TorCheck
-----_ 检查是与否使用 Tor 连接网络
---- Chutney
-----_ Tor 网络测试
---- Compass
-----_ Tor 中继检索、过滤器
---- DocTor
-----_ Tor 中继描述符监控，用于辅助目录管理员
---- ExitMap
-----_ 检查恶意以及错误配置的出口节点
---- Metrics
-----_ Tor 网络数据统计
---- OnionScan
-----_ 帮助隐藏服务检查漏洞
---- Onionoo
-----_ 基于 Web 的中继和网桥状态检索工具
---- Shadow
-----_ Tor 仿真软件
---- TorFlow
-----_ 检查错误配置或行为异常的的节点、网桥
---- TorPS
-----_ Tor 路由选择模拟器
---- Stem
-----_ Python Tor 控制器包
---- Nyx
-----_ Tor 监控工具


@endmindmap